apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'nginx-deployment'
spec:
  template:
      metadata:
        name: pod-nginx
        labels:
          app: nginx
      spec:      
        containers:
          - name: nginx
            image: nginx:2
            ports:
              - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: nginx
